import { EssenceShopItem } from './essence-shop-item';

export const listEssenceShopItem: EssenceShopItem[] = [
  {
    id: 'spawn-more-less-loot',
    name: 'Appât spectral',
    description: 'Les monstres apparaissent 25 % plus souvent, mais leur butin d’essence baisse de 10 %.',
    effectType: 'spawnRate',
    effectValue: 1.35,
    secondaryEssenceMultiplier: 0.9,
    basePrice: 25,
    priceGrowth: 1.55,
    price: 10,
    level: 0,
    bought: false,
  },
  {
    id: 'spawn-less-more-loot',
    name: 'Brume d’éther',
    description: 'Les monstres apparaissent 10 % moins souvent, mais rapportent 25 % d’essence en plus.',
    effectType: 'spawnRate',
    effectValue: 0.9,
    secondaryEssenceMultiplier: 1.35,
    basePrice: 10,
    priceGrowth: 1.55,
    price: 35,
    level: 0,
    bought: false,
  },
  {
    id: 'more-hp-more-loot',
    name: 'Carapace vorace',
    description: 'Les monstres ont 15 % de vie en plus et rapportent 25 % d’essence en plus.',
    effectType: 'hp',
    effectValue: 1.15,
    secondaryEssenceMultiplier: 1.35,
    basePrice: 50,
    priceGrowth: 1.6,
    price: 50,
    level: 0,
    bought: false,
  },
  {
    id: 'less-hp-less-loot',
    name: 'Faim artificielle',
    description: 'Les monstres ont 25 % de vie en moins, mais rapportent 15 % d’essence en moins.',
    effectType: 'hp',
    effectValue: 0.75,
    secondaryEssenceMultiplier: 0.85,
    basePrice: 45,
    priceGrowth: 1.6,
    price: 45,
    level: 0,
    bought: false,
  },
  {
    id: 'less-time-more-loot',
    name: 'Sablier brisé',
    description: 'Le temps pour tuer l’ennemi baisse de 10 %, mais son essence augmente de 20 %.',
    effectType: 'time',
    effectValue: 0.9,
    secondaryEssenceMultiplier: 1.2,
    basePrice: 65,
    priceGrowth: 1.65,
    price: 65,
    level: 0,
    bought: false,
  },
  {
    id: 'more-time-less-loot',
    name: 'Sablier généreux',
    description: 'Le temps pour tuer l’ennemi augmente de 15 %, mais son essence baisse de 10 %.',
    effectType: 'time',
    effectValue: 1.15,
    secondaryEssenceMultiplier: 0.9,
    basePrice: 55,
    priceGrowth: 1.65,
    price: 55,
    level: 0,
    bought: false,
  },
];
