import { requireAll, requireBought, requirePower, requireWorkerLevel, ShopItem } from "./shop-item";
/*
Recap des workers :
- Épée : 0
- Fourche : 1
- Pioche : 2
- Marteau : 3
- Etoile : 4
- Baguette : 5
- Potion : 6
- Machine : 7
- Maison : 8

*/
export const listShopItem: Array<ShopItem> = [
  {
    id: 'shop-sword-training',
    name: 'Epée d\'entrainement',
    description: 'Aussi piquant qu\'un cure-dent, multiplie les dégats de l\'épée définitivement par 1.2',
    imageUrl: 'assets/img/swords/Sword1.png',
    price: 100,
    doesAppearInGame: false,
    bought: false,
    value: 1.2,
    workerIndex: 0,
  },{ 
    id: 'shop-sword-tempered',
    name: 'Epée en bois trempé',
    description: 'Avec de l\'acier trempé, ça aurait été plus efficace, multiplie les dégats de l\'épée définitivement par 1.5',
    imageUrl: 'assets/img/swords/Sword2.png',
    price: 2000,
    doesAppearInGame: false,
    bought: false,
    value: 1.5,
    workerIndex: 0,
    unlockCondition: requireAll(requireBought('shop-sword-training'), requireWorkerLevel(0, 25)),
    requiredWorkerLevelForUnlock: { workerIndex: 0, level: 25 }, 
   },{ 
    id: 'shop-sword-calcaire',
    name: 'Epée en calcaire',
    description: 'Cette épée est un unique exemplaire, certainement parce qu\'elle est inutile. Multiplie les dégats de l\'épée définitivement par 1.2',
    imageUrl: 'assets/img/swords/Sword2.png',
    price: 3000,
    doesAppearInGame: false,
    bought: false,
    value: 1.2,
    workerIndex: 0,
    unlockCondition: requireAll(requireBought('shop-sword-tempered'), requireWorkerLevel(0, 50)),
    requiredWorkerLevelForUnlock: { workerIndex: 0, level: 50 },
  },{ 
    id: 'shop-sword-frangipane',
    name: 'Epée en frangipane',
    description: 'Dans un saladier, mélanger la poudre d\'amandes, le sucre, les 2 oeufs et le beurre mou. Enfourner pendant 20 à 30 min à 200°C (thermostat 6-7); vérifier régulièrement la cuisson ! Multiplie les dégats de l\'épée définitivement par 1.5',
    imageUrl: 'assets/img/swords/Sword1.png',
    price: 1000,
    doesAppearInGame: false,
    bought: false,
    value: 1.5,
    workerIndex: 0,
    unlockCondition: requireAll(requireBought('shop-sword-training'), requireWorkerLevel(1, 10)),
    requiredWorkerLevelForUnlock: { workerIndex: 1, level: 10 },
  },
  {
    name: 'FourcheLangue',
    description: 'Fourche légendaire datant d\'un temps oublié, dommage qu\'elle soit cassée. Multiplie les dégâts du fermier définitivement par 2',
    imageUrl: 'assets/img/Farmer/Farmer1.png',
    price: 50,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 1,
  },{
    name: 'Piochette',
    description: 'Une pioche qui fait mal, elle multiplie les dégâts du mineur définitivement par 2',
    imageUrl: 'assets/img/Miner/Miner1.png',
    price: 1000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 2,
  },
  {
    name: 'Marteau en bois',
    description: 'Un marteau qui fait pas très mal, on pourrait presque l\'appeler un maillet. Il multiplie les dégâts du forgeron définitivement par 2',
    imageUrl: 'assets/img/Smith/Smith1.png',
    price: 10000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 3,
  }, {
    name: 'Etoile en bois',
    description: 'Une étoile qui fait pas très mal, mais elle est très joli. Elle multiplie les dégâts de l\'astrologue définitivement par 2',
    imageUrl: 'assets/img/Star/Star1.png',
    price: 100000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 4,
  },
  {
    name: 'Baguette de boulanger',
    description: 'Très bonne, bien qu\'elle ne soit pas très utile pour le combat. Elle multiplie les dégâts du magicien définitivement par 2.',
    imageUrl: 'assets/img/Wand/Wand1.png',
    price: 1000000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 5,
  },
  {
    name: 'Potion en bois',
    description: 'Cette potion n\'est constitué que de bois, ce qui n\'améliore pas le goût étonnamment. Multiplie les dégâts du alchimiste définitivement par 2.',
    imageUrl: 'assets/img/Potion/Potion1.png',
    price: 10000000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 6,
  },
  {
    name: 'Machine en bois',
    description: 'Une machine qui fait pas très mal, on pourrait presque l\'appeler un maillet. Il multiplie les dégâts du géomètre définitivement par 2',
    imageUrl: 'assets/img/Machine/Machine1.png',
    price: 100000000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 7,
  },
  {
    name: 'Maison en bois',
    description: 'Une belle maison, pas très utile en combat cependant. Elle multiplie les dégâts de l\'architecte définitivement par 2',
    imageUrl: 'assets/img/House/House1.png',
    price: 1000000000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    workerIndex: 8,
  },
  {
    id: 'shop-power-mana',
    name: 'Amulette de mana',
    description: 'Réduit le coût en mana du sort 마법 de 10%.',
    imageUrl: 'assets/img/power/power.png',
    price: 5000,
    doesAppearInGame: false,
    bought: false,
    value: 1,
    unlockCondition: requireWorkerLevel(5, 1),
    requiredWorkerLevelForUnlock: { workerIndex: 5, level: 1 },
    powerId: 'power',
    powerManaFactor: 0.9,
  },
  {
    id: 'shop-mana-max',
    name: 'Cristal de mana',
    description: '+300 mana max.',
    imageUrl: 'assets/img/power/power.png',
    price: 8000,
    doesAppearInGame: false,
    bought: false,
    value: 1,
    unlockCondition: requireWorkerLevel(5, 5),
    requiredWorkerLevelForUnlock: { workerIndex: 5, level: 5 },
    manaMaxBonus: 300,
  },
  {
    id: 'shop-mana-regen',
    name: 'Fontaine de mana',
    description: '+0.05 mana/s de régénération.',
    imageUrl: 'assets/img/power/power.png',
    price: 15000,
    doesAppearInGame: false,
    bought: false,
    value: 1,
    unlockCondition: requireWorkerLevel(5, 10),
    requiredWorkerLevelForUnlock: { workerIndex: 5, level: 10 },
    manaRegenBonus: 0.05,
  },
  {
    id: 'shop-critical-chance',
    name: 'Pierre de chance',
    description: '+1% de chance de coup critique (s\'ajoute au bonus du Mineur).',
    imageUrl: 'assets/img/Miner/Miner1.png',
    price: 2500,
    doesAppearInGame: false,
    bought: false,
    value: 1,
    unlockCondition: requireWorkerLevel(2, 1),
    requiredWorkerLevelForUnlock: { workerIndex: 2, level: 1 },
    unlockUpgrade: { unlockId: 'critical-hit', type: 'chance', value: 0.01 },
  },
  {
    id: 'shop-critical-chance-2',
    name: 'Pierre de chance 2',
    description: '+2% de chance de coup critique (s\'ajoute au bonus du Mineur).',
    imageUrl: 'assets/img/Miner/Miner1.png',
    price: 20000,
    doesAppearInGame: false,
    bought: false,
    value: 2,
    unlockCondition: requireAll(requireBought('shop-critical-chance'), requireWorkerLevel(2, 30)),
    requiredWorkerLevelForUnlock: { workerIndex: 2, level: 30 },
    unlockUpgrade: { unlockId: 'critical-hit', type: 'chance', value: 0.02 },
  },
];

